name: easy_country_picker
description: "A Flutter package which help allow developer to get country related data in one click."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

repository: https://github.com/smile675/easy_country_picker.git


flutter:

